SIMULATOR ?= vcs
TOP ?= tb_top
WORK_DIR ?= work
COMPILE_ARGS ?=
SIM_ARGS ?=

.PHONY: compile run clean

compile:
	@echo "Compiling with $(SIMULATOR)..."
	# TODO: Add simulator-specific compile commands

run: compile
	@echo "Running simulation with $(SIMULATOR)..."
	# TODO: Add simulator-specific run commands

clean:
	@echo "Cleaning build artifacts..."
	rm -rf $(WORK_DIR)
	# TODO: Add simulator-specific cleanup commands
